[album]
title = "POCLANOS ─ Album"
url = "https://poclanos.com/album-list/"
entrySelector = "div.album-container div[class^='album-single']"
titleSelector = "div.alb-title-gr span"
linkSelector = "a"
contentSelector = "a.album-title.album-artist"
imageSelector = "div.album-wrap img"
waitUntil = "networkidle"
onFail = "stale"

[review]
title = "POCLANOS ─ Review"
url = "https://poclanos.com/category/review/"
entrySelector = "article[class^='post']"
titleSelector = "h2.entry-title a"
linkSelector = "h2.entry-title a"
imageSelector = "a.post-thumbnail img"
waitUntil = "networkidle"
onFail = "stale"

[interview]
title = "POCLANOS ─ Interview"
url = "https://poclanos.com/category/interview/"
entrySelector = "article[class^='post']"
titleSelector = "h2.entry-title a"
linkSelector = "h2.entry-title a"
imageSelector = "a.post-thumbnail img"
waitUntil = "networkidle"
onFail = "stale"

[featured]
title = "POCLANOS ─ Featured"
url = "https://poclanos.com/category/featured/"
entrySelector = "article[class^='post']"
titleSelector = "h2.entry-title a"
linkSelector = "h2.entry-title a"
imageSelector = "a.post-thumbnail img"
waitUntil = "networkidle"
onFail = "stale"

[naverpost]
title = "네이버 포스트 ─ 포크라노스"
url = "https://m.post.naver.com/my.naver?memberNo=24373938"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"
onFail = "stale"

[naverpost_poclanos_interview]
title = "POCLANOS ─ 포크라노스 인터뷰"
url = "https://m.post.naver.com/my/series/detail.naver?seriesNo=477212&memberNo=24373938"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[naverpost_poclanos_special]
title = "POCLANOS ─ 뮤직스페셜"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=479308&memberNo=24373938"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"

[naverpost_poclanos_commentary]
title = "POCLANOS ─ 포크라노스 코멘터리"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=477089&memberNo=24373938"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
onFail = "stale"